version: '3'
services:
  mysql:
    image: mysql:latest
    restart : always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sayan
      MYSQL_DATABASE : smartcare
      MYSQL_HOST: 3306

  redis:
    restart : always
    image: redis:latest
    ports:
      - "7778:6379"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kakfa
    ports:
        - '9092:9092'
    environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
